version: '3.4'

services:
  ble_service:
    image: ble_service:latest
    depends_on:
      - "rabbitmq"
    build:
      context: ./BleService
      dockerfile: Dockerfile

  serial_service:
    image: serial_service:latest
    depends_on:
      - "rabbitmq"
    build:
      context: ./SerialService
      dockerfile: Dockerfile

  bluerial:
    image: bluerial_api:latest
    depends_on:
      - "ble_service"
      - "serial_service"
    build:
      context: ./BluerialApi
      dockerfile: Dockerfile

  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"